### ISSUE TITLE
Error importing keystore module

### ISSUE THREAD

**Issue by dafuni** [pshamus/Keystore#1]
It's attempting to open a file in ...\assemblies\12.0 but that folder does not exist. I worked around by copying 11.0 and renaming it to 12. Just letting you onow.
========================================================
Write-Error: Failed to load Keystore module: System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\Users\imoses\Documents\PowerShell\Modules\PSKeystore\PSKeystore\Assemblies\12.0\Newtonsoft.Json.Schema.dll' because it does not exist.
   at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext context)
   at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path, CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
   at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
   at System.Management.Automation.PathIntrinsics.GetResolvedPSPathFromPSPath(String path, CmdletProviderContext context)
   at Microsoft.PowerShell.Commands.ResolvePathCommand.ProcessRecord()

**Comment by pshamus** [comment]
Hey there, thanks for letting me know about this. I haven't worked out a good method of keeping up to date with newer version of Newtonsoft JSON assemblies.
